カレンダープラクティスの提出物になります。
appsu-mi/ruby-practices pull request #2
Opened 2023-09-04 08:06 UTC by appsu-mi

お手数お掛け致しますが
レビューの程よろしくお願いします。

2023-09-10 17:12 UTC, u1tnk requested changes

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  week_a_words.each {|word| print word.center(2)}
centerを色々な事に使っているようですが、「中央寄せ」がしたいときだけ使うようにしましょう。

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    message = "calendar.rb:#{optional_value['m']}  is neither a month number (1..12) nor a name"
ここに来たらもうエラーで中止で良いのでここで終わらせましょう。
また、実装した分はそのままで良いですが、プラクティスでは指定が無ければ想定外の値の対処まではしなくて大丈夫です。

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  elsif optional_value.has_key?('y') && optional_value.has_key?('m')
ここらへんは煩雑になってますね。
optionが無いときは yとmそれぞれで初期値を設定して同じ処理に渡すと良いかと思います。

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  @one_day_space = ''.center(3)
他のメソッドに値を渡すときにインスタンス変数を使うのはNGです。引数で渡すのが良いですね。
データの流れが分からなくなるのが理由です。

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  @one_day_space = ''.center(3)
` @one_day_space` は固定なので定数で良いでしょう

2023-09-10 17:12 UTC, u1tnk commented on 02.calendar/calendar.rb
> +def begin_of_month_positioning
ここは内容に比べてちょっと複雑ですね。

- 空白だけ出力して first_dayの出力は通常の日付出力と共通化した方が単純になります。なるべく一つのメソッドがやることは一つにする方が分かりやすいですね。
- 日曜だけ別処理になってますが、0のときの処理はelse内と結局同じになりそうに見えますがどうでしょうか？
- ここは単純な知識ですが、 ` ` ` * 3` でspace3つになるのでこれを利用すればもっと短く書けると思います。

2023-09-11 10:20 UTC, appsu-mi commented
再度pushしました〜
お手数ですがレビューよろしくお願い致します🙇‍♂️

11行目のここは少し意味が重複してしまったような気がします。
```
#11  puts "\n"
```
```
#11  print "\n"
#11  puts ""
```
こっちの方が良かったでしょうか？
大規模工事でした😅

2023-09-11 16:31 UTC, u1tnk requested changes
だいぶ良くはなったんですが、前回の指摘で対応しきれてないところともうちょっと改善の余地があるのでやってみてください 💪

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    message = "calendar.rb:#{optional_value['m']}  is neither a month number (1..12) nor a name"
ここの対応漏れてますでしょうか？

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +if optional_value['y'].is_a?(String) || optional_value['m'].is_a?(String)
ここは `optional_value['y'] ||= today.year` のところで入力があったときに `to_i`してあれば不要だと思います。

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +      print "#{day}".center(3)
前回も指摘しましたが これは中寄せをしたいわけではなく、「左二枠に右寄せと区切りスペース一文字を主力したい」と思います。
なので、centerを使えば一文字のときも二文字のときも両立はするものの意図が誤解されるのでよく無いです。
(ちなみにcenter(3)に二文字渡すと左に寄るのは私も知りませんでした)

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  week_days = 7
`week_days` と `wday_for_saturday`  は定数にするべきです。
また、rubyのプログラムでは複数系は配列を表すという慣習があるので、別の名前の方が良いと思います。

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  puts "\n"
ここは二回改行するよ！というのを強調したければ `print "\n\n"` の方が分かりやすいかもしれません。
とはいえ大差は無いので、これでも大丈夫です 🙆‍♀️

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  one_day_space = "\s" * 3
これは定数になると思います。
また、"\s" は空白を意味する正規表現では使いますが、文字列としてはあまり使いません。
単にスペースとして使いたいのであれば '" "' の方が迷わなくて良いと思います。
 `"   "` だと「スペース何個あるか見づらいな 🤔 」ってなりますが、 `" " * 3 ` なら十分だと思います。

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    print one_day_space
ここも `print one_day_space * wday_begin_of_month` にできると思います。

2023-09-11 16:31 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    if day == 1
ここはもうちょっとですね。

以下を意識してもうちょっと整理してみましょう。

- 一日目の特別処理は空白を入れるだけのはずです。
- 日付を出力する処理は全パターンで同一にできると思います。
- 土曜になったら改行を出力するというだけのはず
- 変数が多いのも読みづらくなります。row_count_nuberを作らずとも dayから計算で出せると思います。ヒントとしては rubyには割り算の余りを計算することができることです。

2023-09-12 10:50 UTC, appsu-mi commented
お手数お掛け致します🙇‍♂️
ちょっとしたミスがあり2回pushさせていただきました。申し訳ありません🙇‍♂️
再度ご確認の程宜しくお願い致します。
```
unless optional_value['m'].nil?
  unless (1 .. 12).include?(optional_value['m'])
    message = "calendar.rb:#{optional_value['m']}  is neither a month number (1..12) nor a name"
  end
end
```
こちらのコードは、オプションで1~12月以外の月指定をされた時にエラーメッセージを出す、という処理になっています。とりあえずはなくても動く（漏れはない）ので、削除させていただきました。


### 1つ質問をさせていただきたいです！
定数を使う際の基準についてです。

* 定数を使う際の判断はどこでしているのか？ということをお聞きしたいです。
例えば、今回のこのコードですね。
```
ONE_DAY_SPACE = " " * 3
```
僕は「一箇所でしか使っていないしローカル変数を使おう」と判断してしまったのですが、
この場面で定数を使うべき理由を教えていただきたいです！
他で使う可能性があるからということでしょうか？
宜しければお答えいただけますと幸いです🙇‍♂️

2023-09-12 13:54 UTC, u1tnk commented
> ちょっとしたミスがあり2回pushさせていただきました。申し訳ありません🙇‍♂️
再度ご確認の程宜しくお願い致します。

pushを二回するのは特に問題ありません。というかこまめにpushしても大丈夫です。

> 僕は「一箇所でしか使っていないしローカル変数を使おう」と判断してしまったのですが、
この場面で定数を使うべき理由を教えていただきたいです！
他で使う可能性があるからということでしょうか？

ここで生の数値ではなく定数なのは以下のようにただの数値だと分かりづらいから一回しか使ってなくても説明の為に定数にします。

https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0)

ただ、 「一箇所でしか使っていないしローカル変数を使おう」 というように元々変数でしたね。

まず、変数と定数では変数は「何が入っているのか？途中で変わるのか？」という点で読みづらくなります。
変わる値がたくさんあるほど混乱しますので。
なので、絶対に変わらない値であれば基本的に変数ではなく定数を使います。

2023-09-12 14:29 UTC, u1tnk requested changes

2023-09-12 14:29 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    day < 10 ? print("#{day}".center(3)) : print("#{day}".ljust(3))
centerを使わないでくださいと書くの3回目なので対応お願いします 🙏 
まが、 ljustを使ってますが、左寄せなのも微妙です。
というか `day < 10`で判定しているのであればcenterもljustも使う必要は無いです。
やりたいことは 「数値を表示したい固定の二文字サイズに右寄せ」＋「余白」なので、その意図をコードに反映させてください。

2023-09-12 14:29 UTC, u1tnk commented on 02.calendar/calendar.rb
> +      print "\n"
ここは二箇所同じなので、 elsifでなく `||` なので良いのではと思います。
細かいですし、mustでも無いですが  `WEEK_DAY - wday_begin_of_month` はちょっと長いので、これは変数に入れても良さそうに思います。

2023-09-12 22:40 UTC, appsu-mi commented
申し訳ありませんでした🙇‍♂️
再push致しましたのでご確認の程よろしくお願い致します。

2023-09-13 11:23 UTC, appsu-mi commented
> 数値を表示したい固定の二文字サイズに右寄せ

というのがどうにもわかりません。。
もうちょっと修正してみます。

2023-09-13 12:44 UTC, mousu-a commented
push致しました。
出来た気がします...!
ご確認の程よろしくお願いいたします🙇‍♂️

2023-09-13 15:02 UTC, u1tnk approved these changes

2023-09-13 15:02 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    print day.strftime('%e') + ' '
ちょっと想定と違いましたが、それ用のフォーマットだしＯＫです！
想定としては今の変数状況だと `print day.day.to_s.rjust(2) + ' '` あたりでした。

2023-09-13 16:03 UTC, merged